[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\ballard-arinc-429-custom-device'

[projects.cd]
path = 'Source\Ballard Arinc-429 Custom Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2020_release_branches = ["master",]

[package]
type = 'nipkg'
name = 'ballard-arinc-429-custom-device-{veristand_version}'
dev_xml_path = 'Source\Custom Device Ballard - Arinc-429.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices'
